name: Test and Lint Laravel App

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ani
          POSTGRES_PASSWORD: password
          POSTGRES_DB: anikultura
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Attempt to execute database migrations
        run: php artisan migrate:fresh

      - name: Attempt to execute database seeders
        run: php artisan db:seed

      - name: Attempt to generate Swagger documentation
        run: php artisan l5-swagger:generate

      - name: Create testing database
        run: psql -f database/init.sql postgresql://ani:password@postgres:5432/postgres

      - name: Execute tests
        run: composer test

      - name: Verify linting
        run: composer sniff
